<?php

/**
 * @file
 * Patch for mavic
 */

/**
 * Implementation of hook_menu().
 */
function mavicpatch_menu() {
	$items['admin/settings/mavicpatch'] = array(
		'title' => 'Mavic Patch',
		'page callback' => 'mavicpatch_data',
		'access arguments' => array('administer menu'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}


//-----------------------------------------------------------------------------------------------

/**
 * excel news tabs
 */
function mavicpatch_data() { 
	$res = db_query('select c.field_news_date_value, c.nid from {content_type_news} c');
	$i = 0;
	while ($node = db_fetch_array($res)) {
		$day = substr($node['field_news_date_value'],8,2);
		$month = substr($node['field_news_date_value'],5,2);
		$year2 = substr($node['field_news_date_value'],2,2);
		$shortDate = ($day+($month-1)*31+$year2*372)*-1;
		db_query('update {menu_links} set weight=' . $shortDate . ' where link_path ="node/' . $node['nid'] . '"');
		$i++;
	}
	$output = "$i news updated";
	return $output;
}
